Legal-Innovation-Lab-Wales/include-journey

db/migrate/20210225200409_devise_create_users.rb, db/schema.rb
Updated the create users migration to include all of the additional fields users can have set according to our ERD setup.
=> IJ-59 Add custom fields to user

db/migrate/20210225200409_devise_create_users.rb, db/migrate/20210225203142_devise_create_team_members.rb, db/schema.rb
Updated the create team_members migration to include all of the additional fields team_members can have set according to our ERD setup.
=> IJ 60 Add custom fields to team_member

app/assets/stylesheets/global.scss, app/assets/stylesheets/variables.scss, app/helpers/application_helper.rb, app/views/layouts/application.html.erb
Added basic navbar and alerts. 
Only created roughly at first as they will need refining later on.
=> Feature/IJ-12 - Front end framework

app/assets/stylesheets/forms.scss, app/assets/stylesheets/global.scss, app/assets/stylesheets/variables.scss, app/views/layouts/application.html.erb, app/views/team_members/confirmations/new.html.erb, app/views/team_members/passwords/edit.html.erb, app/views/team_members/passwords/new.html.erb, app/views/team_members/registrations/edit.html.erb, app/views/team_members/registrations/new.html.erb, app/views/team_members/sessions/new.html.erb, app/views/team_members/shared/_links.html.erb, app/views/team_members/unlocks/new.html.erb, app/views/users/confirmations/new.html.erb, app/views/users/passwords/edit.html.erb, app/views/users/passwords/new.html.erb, app/views/users/registrations/edit.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb, app/views/users/shared/_links.html.erb, app/views/users/unlocks/new.html.erb
Updated all of the devise views to use a centered bootstrap form template that includes floating labels for the input fields and the Include UK colours for the buttons and links.
=> IJ 29 devise views

app/controllers/team_members/crisis_events_controller.rb, app/controllers/team_members/users_controller.rb, app/controllers/users/journal_entries_controller.rb, app/controllers/users/users_application_controller.rb
Where a message is not a warning but rather just information to be shown to a user I've changed the type from alert to notice.
=> Alerts to notice update

app/controllers/pages_controller.rb, app/controllers/team_members/team_members_application_controller.rb, app/controllers/users/users_application_controller.rb, app/views/pages/main.html.erb, config/routes.rb
=> IJ-83 Added home page routes for authenticated users.

app/views/team_members/team_members/index.html.erb
Fix for validation token error being caused by approve/admin buttons being embedded as hidden forms.
=> IJ-120 - Bugfix

app/assets/stylesheets/global.scss, app/assets/stylesheets/team_members.scss, app/controllers/pages_controller.rb, app/controllers/team_members/team_members_application_controller.rb, app/controllers/team_members/team_members_controller.rb, app/helpers/wba_self_permissions_helper.rb, app/helpers/wba_self_scores_helper.rb, app/helpers/wba_self_view_logs_helper.rb, app/helpers/wba_team_member_scores_helper.rb, app/helpers/wba_team_members_helper.rb, app/helpers/wellbeing_assessments_helper.rb, app/views/team_members/team_members/index.html.erb, config/routes.rb, db/migrate/20210225203142_devise_create_team_members.rb, db/schema.rb, db/seeds.rb
I've added in the ability for admins to pause team member accounts via a button on the team members index. This button has a confirmation warning explaining that the team member will be locked out of the system whilst paused and the team member is informed when they attempt to access the system why that can't.
I've also gone ahead and removed the box-shadow properties from all buttons whilst here which is IJ-91.
=> IJ-97 + IJ-91 

app/assets/stylesheets/team_members.scss, app/controllers/team_members/team_members_controller.rb, app/views/team_members/team_members/index.html.erb, config/routes.rb
Admin team members can now also reject team member sign ups which will destroy that team member record. I've also fixed the flash messages not appearing if they're of any type other than notice.
=> IJ-98 - Team Member Rejection

app/assets/stylesheets/contacts.scss, app/controllers/users/contacts_controller.rb, app/views/users/contacts/_form.erb, app/views/users/contacts/edit.html.erb, app/views/users/contacts/index.html.erb, app/views/users/contacts/new.html.erb
Fixed the contacts index using the old pagination setup, updated styling on the new/edit form to match that of the IJ-forms.
=> Contacts Pagination Fix

app/controllers/team_members/wellbeing_assessments_controller.rb, app/javascript/packs/back.js, app/javascript/packs/view_mode.js, app/views/shared/_back_btn.html.erb, app/views/team_members/crisis_events/active.html.erb, app/views/team_members/crisis_events/index.html.erb, app/views/team_members/crisis_events/show.html.erb, app/views/team_members/journal_entries/index.html.erb, app/views/team_members/journal_entries/show.html.erb, app/views/team_members/journal_entry_view_logs/index.html.erb, app/views/team_members/team_members/index.html.erb, app/views/team_members/team_members/show.html.erb, app/views/team_members/users/index.html.erb, app/views/team_members/users/show.html.erb, app/views/team_members/wellbeing_assessments/index.html.erb, app/views/team_members/wellbeing_assessments/new.html.erb, app/views/team_members/wellbeing_assessments/show.html.erb, app/views/users/contacts/edit.html.erb, app/views/users/contacts/index.html.erb, app/views/users/contacts/new.html.erb, app/views/users/journal_entries/dashboard.html.erb, app/views/users/journal_entries/index.html.erb, app/views/users/journal_entries/new.html.erb, app/views/users/wellbeing_assessments/new.html.erb, app/views/users/wellbeing_assessments/show.html.erb
Back button now leverages the history.back function so the user won't be able to get stuck in loops. I've also fixed a bug with searching the wellbeing assessments where the subheading stats aren't explicitly stating the create_at column on the wellbeing assessments table which it needs to if that table has been joined with the user table as is done when searching.
=> IJ-142 Back Button Fix

app/assets/stylesheets/journal_entries.scss, app/views/users/journal_entries/new.html.erb
=> IJ-153 - Added new emoji to represent super excited.

app/assets/stylesheets/wellbeing_metrics.scss, app/javascript/packs/wellbeing_assessment_chart.js
Updated the colour scale for wellbeing assessment charts as some colours looked imperceptible.
=> Updated color scale for wellbeing assessment charts

app/assets/stylesheets/forms.scss, app/assets/stylesheets/modals.scss, app/assets/stylesheets/pages.scss, app/views/modals/crisis_events/_existing.html.erb, app/views/modals/crisis_events/_new.html.erb, app/views/modals/devise/_modal.html.erb, app/views/pages/about.html.erb, app/views/team_members/confirmations/new.html.erb, app/views/team_members/passwords/new.html.erb, app/views/team_members/registrations/edit.html.erb, app/views/team_members/registrations/new.html.erb, app/views/team_members/sessions/new.html.erb, app/views/team_members/shared/_back_to_login.html.erb, app/views/team_members/shared/_links.html.erb, app/views/team_members/unlocks/new.html.erb, app/views/users/confirmations/new.html.erb, app/views/users/passwords/new.html.erb, app/views/users/registrations/edit.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb, app/views/users/shared/_back_to_login.html.erb, app/views/users/shared/_links.html.erb, app/views/users/unlocks/new.html.erb, config/routes.rb
Re-designed the login page for the platform as the original view was very overcrowded:
The root route has been changed to the User login page. The new design is a lot more concise and clean looking:
The extra links on the old login forms have been extracted out into a modal, accessed through the 'Trouble Signing In?' linkl.
Before:
After: 
By clicking 'Learn More', you will be redirected to the 'About' section, where you detailed descriptions of the project, Include and the Lab can be found:
The Team Member login is as follows. It can be found by clicking the link in the top right of User login. Similarly, you can navigate back to the User login by a link in the top right.
Mobile layout:
Currently, the only differences between the User login and the Team Member login are the Icons in the …
=> Feature/IJ-170 Login Redesign

app/controllers/team_members/wellbeing_services_controller.rb, app/views/shared/wellbeing_services/_card.html.erb, app/views/team_members/users/_card.html.erb, app/views/team_members/wellbeing_services/_form.html.erb, app/views/team_members/wellbeing_services/index.html.erb, app/views/users/wellbeing_services/index.html.erb, db/migrate/20210407142950_create_wellbeing_services.rb, db/schema.rb, db/seeds/01_team_members.rb, db/seeds/02_wellbeing_metrics.rb, db/seeds/03_wellbeing_services.rb, db/seeds/04_metrics_services.rb, db/seeds/05_crisis_types.rb, db/seeds/06_goal_types.rb, db/seeds/07_users.rb, db/seeds/08_user_profile_view_logs.rb, db/seeds/09_wellbeing_assessments.rb, db/seeds/10_wba_scores.rb, db/seeds/11_journal_entries.rb, db/seeds/12_journal_entry_permissions.rb, db/seeds/13_journal_entry_view_logs.rb, db/seeds/14_contacts.rb, db/seeds/15_goals.rb, db/seeds/16_appointments.rb, db/seeds/17_notes.rb, db/seeds/18_crisis_events.rb, db/seeds/19_crisis_notes.rb
Add phone number to the wellbeing services. 
Moved the wellbeing services card to shared/  instead of team members/ as it is used by team members and users.
Also included a fix for a broken link and a small update to the output when seeds run.
=> Feature - IJ-188 add phone number wellbeing services

app/views/shared/_navbar.html.erb, app/views/shared/wellbeing_chart/_description.html.erb, app/views/team_members/dashboard/show.html.erb, app/views/team_members/wellbeing_metrics/index.html.erb, app/views/team_members/wellbeing_score_values/index.html.erb, app/views/team_members/wellbeing_services/index.html.erb, db/seeds.rb, db/seeds/01_team_members.rb, db/seeds/02_wellbeing_metrics.rb, db/seeds/03_wellbeing_services.rb, db/seeds/04_metrics_services.rb, db/seeds/05_crisis_types.rb, db/seeds/06_goal_types.rb, db/seeds/07_users.rb, db/seeds/08_user_profile_view_logs.rb, db/seeds/09_wellbeing_assessments.rb, db/seeds/10_wellbeing_score_values.rb, db/seeds/11_wba_scores.rb, db/seeds/12_journal_entries.rb, db/seeds/13_journal_entry_permissions.rb, db/seeds/14_journal_entry_view_logs.rb, db/seeds/15_contacts.rb, db/seeds/16_goals.rb, db/seeds/17_appointments.rb, db/seeds/18_notes.rb, db/seeds/19_crisis_events.rb, db/seeds/20_crisis_notes.rb, db/seeds/21_tags.rb, db/seeds/22_user_tags.rb
Building off the work @AlexW555 has done I've made some minor style updates that I think add to this work, firstly I've updated the seeds to use 2 `pretty_print` functions for the entity names and the times to ensure the print out is always consistently laid out and not require the developer to trial and error the no. of tab characters needed to get everything to align.
Secondly I've added an additional hidden button to the dashboard so the wellbeing management and tags buttons are the same size as the others, I realise this does leave us with a gap (2 for non-admins) but I still think this looks better (ideally we'd center align these so if you have a single button on the bottom row it looks like the 0 key on a telephone keyboard for example).
Thirdly I've removed showing the value on …
=> Feature - IJ-182 Minor Updates

app/views/shared/wellbeing_chart/_description.html.erb, app/views/shared/wellbeing_chart/_sliders.html.erb, app/views/users/wellbeing_assessments/new.html.erb, app/views/users/wellbeing_assessments/show.html.erb
Reverted the changes made to the description partial as this never took into account the impact on the new form for WBA's. 
I've also made the same changes to the show view as were made for the new view to change how the 'Your Services' buttons appear and look.
=> Bugfix - IJ-191 - Reverting changes.

app/assets/stylesheets/users.scss, app/models/user.rb, app/views/team_members/users/_card.html.erb, app/views/team_members/users/show.html.erb, db/migrate/20210528104757_add_deleted_field.rb, db/schema.rb
When a user deletes their account rather than removing the user record the record is now marked as deleted and the associated resources which could contain identifying information are removed. Similarly the first and last names are removed along with the email and mobile number for the user.
Demo:
https://user-images.githubusercontent.com/6815945/128047104-d104bca9-fd8c-4aa5-8f90-a9af1d364286.mov
I've also updated the user index cards to show in all-red in the case of a deleted user:
=> Feature - IJ 196 Update Delete Functionality

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/models/user.rb, app/views/layouts/mailer.html.erb
Fixed a bug with the sign out notice where it only expected to appear on the pages/main template.
=> Bugfix - IJ-197 Team Member Sign Out Notice

db/seeds/01_team_members.rb
Adding a new team member to the 'root/db/seeds/01_team_members.rb’ so that I can use the details to test the include journey app on my local device.
[Ticket: IJ-232](https://lilw.atlassian.net/browse/IJ-232)
=> IJ-232: Add new account details for testing team member side of app

app/views/pages/terms.html.erb, db/seeds/01_team_members.rb
Update the already existing Term of Use page with the correct information.
[Ticket: IJ-233](https://lilw.atlassian.net/browse/IJ-233)
=> IJ-233: Update Terms of Use with the Correct Information

app/controllers/team_members/team_members_application_controller.rb, app/controllers/users/users_application_controller.rb, app/views/layouts/application.html.erb, app/views/pages/privacy_notice.html.erb, app/views/pages/terms.html.erb, config/routes.rb, db/seeds/01_team_members.rb
- Creating a route for the privacy notice page
- Adding action to render privacy notice page
- Creating the privacy notice page
- Creating links to view the privacy notice page
- Populating the privacy notice page with correct information.
[Ticket: IJ-234](https://lilw.atlassian.net/browse/IJ-234)
=> IJ-234: Create and Populate Privacy Notice Page

app/controllers/application_controller.rb, app/controllers/team_members/users_controller.rb, app/models/user.rb, app/views/team_members/users/_card.html.erb, app/views/team_members/users/_sort_bar.html.erb, app/views/team_members/users/edit.html.erb, app/views/team_members/users/show.html.erb, app/views/users/registrations/edit.html.erb, app/views/users/registrations/new.html.erb, db/migrate/20230130130725_remove_released_at_from_user.rb, db/schema.rb, db/seeds.rb, db/seeds/06_users.rb, yarn.lock
=> remove released_at instances on ui

app/controllers/team_members/contact_logs_controller.rb, app/controllers/team_members/users_controller.rb, app/views/team_members/contact_logs/_card.html.erb, app/views/team_members/contact_logs/recent.erb, app/views/team_members/users/show.html.erb, config/routes.rb
Enable team members to see the list of contact a specific user has had
=> Enable team members to see the list of contact a specific user has had

app/controllers/team_members/notes_controller.rb
add breadcrumbs to notes contoller
=> add breadcrumbs to notes contoller

app/controllers/team_members/wellbeing_services_controller.rb, app/models/wellbeing_service.rb, app/views/team_members/wellbeing_services/_form.html.erb, app/views/users/wellbeing_assessments/new.html.erb, db/migrate/20230202225741_add_recommend_to_wellbeing_services.rb, db/schema.rb
Add a checkbox to recommend well-being services to users.
[Ticket: IJ-255](https://lilw.atlassian.net/browse/IJ-255)
=> IJ-255:  Add checkbox to recommend wellbeing services to users

app/controllers/team_members/analytics_controller.rb
fix parameter and spelling bug
=> fix parameter and spelling bug

Gemfile, app/controllers/users/registrations_controller.rb, app/views/users/registrations/new.html.erb, config/initializers/recaptcha.rb
=> add recaptcha to signup page

app/controllers/users/goals_controller.rb, app/views/users/goals/_control.html.erb, app/views/users/goals/_form.html.erb, app/views/users/goals/_list.html.erb
hide goal category from UI, change tick button to an ellipse
=> hide goal category from UI, change tick button to an ellipse

Gemfile, Gemfile.lock, app/assets/stylesheets/forms.scss, app/assets/stylesheets/two-factor.scss, app/controllers/concerns/authenticate_with_otp_two_factor.rb, app/controllers/team_members/sessions_controller.rb, app/controllers/team_members/team_members_application_controller.rb, app/controllers/team_members/two_factor_settings_controller.rb, app/helpers/qr_code_helper.rb, app/models/team_member.rb, app/views/shared/_breadcrumbs.html.erb, app/views/team_members/dashboard/show.html.erb, app/views/team_members/registrations/edit.html.erb, app/views/team_members/sessions/new.html.erb, app/views/team_members/sessions/set_up_two_factor.html.erb, app/views/team_members/sessions/two_factor.html.erb, app/views/team_members/two_factor_settings/edit.html.erb, app/views/team_members/two_factor_settings/new.html.erb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20230209090824_add_devise_two_factor_to_team_members.rb, db/migrate/20230209091252_add_devise_two_factor_backupable_to_team_members.rb, db/schema.rb
Team members can set up two-factor authentication.
Also, they are blocks of codes commented out to enable developers to disable and enable two-factor authentication for testing purposes.
[Ticket: IJ-253](https://lilw.atlassian.net/browse/IJ-253)
=> IJ-253: set up two factor authentication

app/assets/stylesheets/team_members/approvals.scss, app/controllers/application_controller.rb, app/controllers/team_members/approvals_controller.rb, app/controllers/team_members/contact_logs_controller.rb, app/controllers/team_members/users_controller.rb, app/controllers/users/registrations_controller.rb, app/helpers/team_members/approvals_helper.rb, app/javascript/packs/approvals.js, app/mailers/admin_mailer.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/views/admin_mailer/new_team_member_email.html.erb, app/views/modals/devise/_modal.html.erb, app/views/shared/_dashboard_btn.html.erb, app/views/shared/_navbar.html.erb, app/views/team_members/approvals/index.html.erb, app/views/team_members/dashboard/show.html.erb, app/views/user_mailer/approved.html.erb, app/views/user_mailer/rejected.html.erb, config/routes.rb, db/migrate/20230213133110_add_approved_to_user.rb, db/migrate/20230215095939_remove_devise_confirmation_from_users.rb, db/schema.rb, spec/helpers/team_members/approvals_helper_spec.rb, spec/requests/team_members/approvals_spec.rb
=> Ij 245 staff verify user emails

app/controllers/application_controller.rb, app/controllers/team_members/users_controller.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/views/team_members/users/edit.html.erb, app/views/user_mailer/suspended.html.erb, config/routes.rb, db/migrate/20230216142515_add_suspended_to_user.rb
enable team members to suspend and re instate users
=> Ij 271 enable team members to suspend and re instate users

app/controllers/users/wellbeing_services_controller.rb
Postcode information wasn't being processed at all if a 'query' existed for the name of the service.
Fulfils this ticket: https://lilw.atlassian.net/browse/IJ-277?atlOrigin=eyJpIjoiMWNlYjdkMjQ3ZWQ1NGVkZTg2NDE4NGE5MjdhY2Y3ODIiLCJwIjoiaiJ9
=> Fixed sort bug

app/controllers/team_members/contact_logs_controller.rb, app/views/team_members/contact_logs/new.html.erb, config/routes.rb
=> fix redirection bug

app/controllers/team_members/contact_logs_controller.rb, app/controllers/users/appointments_controller.rb, app/javascript/packs/start_end_datetime_picker.js, app/javascript/packs/survey_date.js, app/views/team_members/surveys/new.html.erb
Fix date issues on appointment and contact logs
=> Ij 279 date issue

app/controllers/concerns/pagination.rb, app/controllers/team_members/affirmations_controller.rb, app/controllers/team_members/analytics_controller.rb, app/controllers/team_members/appointments_controller.rb, app/controllers/team_members/contact_logs_controller.rb, app/controllers/team_members/diary_entries_controller.rb, app/controllers/team_members/notes_controller.rb, app/controllers/team_members/survey_application_controller.rb, app/controllers/team_members/team_members_controller.rb, app/controllers/team_members/user_tags_controller.rb, app/controllers/team_members/users_controller.rb, app/controllers/team_members/wellbeing_assessments_controller.rb, app/controllers/team_members/wellbeing_metrics_controller.rb, app/controllers/team_members/wellbeing_services_controller.rb, app/controllers/users/contacts_controller.rb, app/controllers/users/goal_permissions_controller.rb, app/controllers/users/goals_controller.rb, app/controllers/users/surveys_controller.rb, app/controllers/users/wellbeing_assessments_controller.rb
=> sanitize query parameters

config/environments/demo.rb, config/environments/development.rb, config/environments/production.rb
modify text_area regex to allow newline
=> modify text_area regex to allow newline

app/controllers/team_members/assign_users_controller.rb, app/javascript/packs/assign_users.js, app/models/team_member.rb, app/models/user.rb, app/views/team_members/assign_users/index.html.erb, app/views/team_members/team_members/show.html.erb, config/routes.rb, db/migrate/20230530172149_add_team_member_to_users.rb, db/schema.rb
implement assign users to team_members feature
=> implement assign users to team_members feature

app/assets/stylesheets/navbar.scss, db/schema.rb
Quick fix for this ticket: https://lilw.atlassian.net/browse/IJ-290?atlOrigin=eyJpIjoiMjI5NzFjNzZkZmE2NDgxNTk1ZDBlMmRlOGYxMDJiMGMiLCJwIjoiaiJ9
=> Increased max width of navbar rollover buttons

app/assets/stylesheets/forms.scss, app/controllers/application_controller.rb, app/controllers/users/registrations_controller.rb, app/views/team_members/users/show.html.erb, app/views/team_members/users/summary_panel/_modal.html.erb, app/views/users/registrations/edit.html.erb
Included pen profile in the user profile page so that users can add a summary about themselves. Made the pen profile mainly a user feature that team members can edit.
[Ticket: IJ-295](https://lilw.atlassian.net/browse/IJ-295)
=> IJ-295: Edit Pen Profile

app/views/users/registrations/edit.html.erb
Fulfils this ticket: https://lilw.atlassian.net/browse/IJ-320
=> IJ-320: Bugfix

Gemfile.lock
Just added the gemfile.lock cos it requested for it on heroku
=> add gemfile.lock

app/controllers/team_members/approvals_controller.rb, app/controllers/team_members/users_controller.rb, app/views/shared/_navbar.html.erb, db/seeds/01_team_members.rb
This restricts team members from viewing users that are not assigned to them.
Fulfils this ticket: https://lilw.atlassian.net/browse/IJ-208
=> IJ-208: Restrict team member view to assigned users

app/views/layouts/application.html.erb
Adds Gemma's information to footer
[Ticket: IJ-312](https://lilw.atlassian.net/browse/IJ-312)
=> IJ-212: Add Gemma's Information To Footer

app/views/team_members/wellbeing_assessments/_card.html.erb
This ticket improves the way we show the creation date on wellbeing assessment cards. It helps team members understand exactly when each assessment was done.
[Ticket: IJ-207](https://lilw.atlassian.net/browse/IJ-207)
=> make date more descriptive

app/views/team_members/analytics/_export_btn.html.erb, app/views/team_members/analytics/_filter_selection.html.erb, app/views/team_members/analytics/index.html.erb
This ticket fixes some styling issues.
[Ticket: IJ-198](https://lilw.atlassian.net/browse/IJ-198)
=> IJ-198: Fix analytics styling
